title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://qemu-gazebo-sim.github.io

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/qemu-gazebo-sim/qemu-gazebo-sim.github.io


