title: QEMU Gazebo Sim 
description: QEMU Gazebo Sim Bachelor Thesis template for a Jeykll site using the Just the Docs theme!

remote_theme: "just-the-docs/just-the-docs@v0.10.0"
color_scheme: neodark

url: https://qemu-gazebo-sim.github.io

logo: https://raw.githubusercontent.com/qemu-gazebo-sim/qemu-gazebo-sim.github.io/main/assets/main_symbol.png

aux_links:
    "QEMU Gazebo Sim on GitHub":
        - "//qemu-gazebo-sim.github.io"